export type Grade = 1 | 2 | 3 | 4 | 5 | 6;

export type Subject = 
  | 'Bahasa Indonesia'
  | 'IPAS'
  | 'Matematika'
  | 'Pendidikan Pancasila'
  | 'Bahasa Inggris'
  | 'PJOK'
  | 'Pendidikan Agama Islam'
  | 'Pendidikan Agama Kristen'
  | 'SBDP';

export interface StudentScore {
  studentName: string;
  diagnostik: number;
  formatif: number;
  sumatif: number;
}

export interface PerformanceInsight {
  summary: string;
  strengths: string[];
  recommendations: string[];
  visualData: {
    category: string;
    average: number;
  }[];
}

export type DesignTemplate = 'modern' | 'classic' | 'creative' | 'technical';

export interface RPMData {
  id: string;
  grade: Grade;
  subject: Subject;
  topic: string;
  semester: 1 | 2;
  schoolName: string;
  teacherName: string;
  teacherNip?: string;
  principalName?: string;
  principalNip?: string;
  academicYear: string;
  meetings: number;
  studentCount: number;
  timeAllocation: string;
  capaianPembelajaran?: string;
  tujuanPembelajaran?: string;
  pgCount?: number;
  essayCount?: number;
  isianCount?: number;
  date: string;
  createdAt: number;
  content: string; // Markdown content generated by AI
  template: DesignTemplate;
  assessments?: StudentScore[];
  insight?: PerformanceInsight;
}
